name: Create Package
description: An action that creates a compressed file for distribution
inputs:
  files:
    description: A list of files to compress
    required: true
  output-file:
    description: The path to output the compressed file at
    required: false
    default: ./release.zip
outputs:
  output:
    description: The path to the result
runs:
  using: node12
  main: src/index.js