name: Create Package
description: An action that creates a compressed file for distribution
inputs:
  config:
    description: The configuration file; must be in JSON format
    required: false
    default: ./create-package-action-config.json
outputs:
  path:
    description: The path to the result zip file
runs:
  using: node12
  main: src/index.js