name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
        submodules: recursive
      - name: install dependencies
        shell: bash
        run: |
          npm install
      - name: create files
        shell: bash
        run: |
          echo a > 1.txt
          echo b > 2.txt
          echo c > 3.txt
      - name: test action
        id: test
        uses: ./
        with:
          config: examples/basic-usage/example.json
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: ${{ steps.test.outputs.path }}